djangotutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('video/', include('video.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video/urls.py
from django.urls import path
from video import views

app_name = "videos"

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('<int:pk>/', views.VideoView.as_view(), name="video"),
]

video/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=200, verbose_name="Başlık")
    desc = models.TextField(verbose_name="Açıklama")

    class Meta:
        verbose_name = "Kategori"
        verbose_name_plural = "Kategoriler"

    def __str__(self):
        return self.title


class Video(models.Model):
    category = models.ForeignKey(Category, null=True, on_delete=models.CASCADE, verbose_name="Kategori")
    title = models.CharField(max_length=200, verbose_name="Başlık")
    desc = models.TextField(verbose_name="Açıklama")
    file = models.FileField(verbose_name="Video Konumu", upload_to="videos/%Y/%m")

    class Meta:
        verbose_name = "Video"
        verbose_name_plural = "Videolar"

    def __str__(self):
        return self.title

video/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from video.models import Video


class GlobalMixin(object):
    def get_context_data(self, *args, **kwargs):
        context = super(GlobalMixin, self).get_context_data(*args, **kwargs)
        context['video_list'] = Video.objects.all().order_by('pk')
        return context


class IndexView(GlobalMixin, generic.ListView):
    template_name = 'index.html'
    model = Video
    context_object_name = 'videos'


class VideoView(GlobalMixin, generic.DetailView):
    template_name = 'video.html'
    model = Video

    def get_context_data(self, *args, **kwargs):
        context = super(VideoView, self).get_context_data(*args, **kwargs)
        context['hello'] = "Hello World"
        context['video_list'] = Video.objects.all().order_by('-pk')
        return context

video/templates/index.html
<h1>Merhaba Dünya</h1>
<h2>Nasılsın? İyi misin? Havalar Nasıl?</h2>
<ul>
  {% for i in videos %}
    <li><a href="{% url 'videos:video' i.pk %}">{{ i.title }}</a> </br> - {{ i.desc }}</li>
  {% endfor %}
</ul>
<ul>
	{% for i in video_list %}
		<li>{{ i.title }}</li>
	{% endfor %}
</ul>

video/templates/video.html
<h1>{{ video.title }}</h1>
<h2>{{ hello }}</h2>
<h3>{{ video.category }}</h3>
<video width="600px" height="auto" src="{{ video.file.url }}"></video>
<p>{{ video.desc }}</p>
<ul>
	{% for i in video_list %}
		<li>{{ i.title }}</li>
	{% endfor %}
</ul>